use super::asset::StatusIconDataAsset;
use bevy::asset::LoadState;
use bevy::prelude::*;

#[derive(Resource)]
pub struct StatusIconCatalog {
    data: lifthrasir_data::StatusIconData,
}

impl StatusIconCatalog {
    pub fn new(data: lifthrasir_data::StatusIconData) -> Self {
        Self { data }
    }

    /// The `ro://` texture path for an EFST's icon, or `None` when the status is
    /// name-only (empty image) or absent from the catalog. A `None` result is a
    /// UI placeholder, not an error.
    pub fn icon_path(&self, efst: u32) -> Option<String> {
        let entry = self.data.icons.get(&efst)?;
        (!entry.image.is_empty()).then(|| format!("ro://data/texture/effect/{}", entry.image))
    }

    /// The English display name for an EFST, or `None` when it is empty or the
    /// status is absent from the catalog.
    pub fn name(&self, efst: u32) -> Option<&str> {
        let entry = self.data.icons.get(&efst)?;
        (!entry.name.is_empty()).then_some(entry.name.as_str())
    }
}

#[derive(Resource)]
pub struct StatusIconDataHandle(Handle<StatusIconDataAsset>);

pub fn start_loading_status_icons(mut commands: Commands, asset_server: Res<AssetServer>) {
    let handle = asset_server.load("data/ron/status_icons.ron");
    commands.insert_resource(StatusIconDataHandle(handle));
    debug!("Loading status icon data RON");
}

pub fn process_loaded_status_icons(
    mut commands: Commands,
    handle: Option<Res<StatusIconDataHandle>>,
    status_icon_assets: Res<Assets<StatusIconDataAsset>>,
    asset_server: Res<AssetServer>,
) {
    let Some(handle) = handle else { return };

    if let LoadState::Failed(err) = asset_server.load_state(&handle.0) {
        error!(
            "Failed to load data/ron/status_icons.ron: {:?}. It is generated by ro-to-lifthrasir-cli.",
            err
        );
        commands.remove_resource::<StatusIconDataHandle>();
        return;
    }

    let Some(asset) = status_icon_assets.get(&handle.0) else {
        return;
    };

    commands.insert_resource(StatusIconCatalog::new(asset.0.clone()));
    commands.remove_resource::<StatusIconDataHandle>();
    debug!("Status icon catalog created from RON");
}

#[cfg(test)]
mod tests {
    use super::*;
    use lifthrasir_data::{StatusIconData, StatusIconEntry};

    fn catalog() -> StatusIconCatalog {
        let mut data = StatusIconData::default();
        data.icons.insert(
            10,
            StatusIconEntry {
                image: String::new(),
                name: "Blessing".to_string(),
            },
        );
        data.icons.insert(
            140,
            StatusIconEntry {
                image: "FOO.tga".to_string(),
                name: "Foo".to_string(),
            },
        );
        StatusIconCatalog::new(data)
    }

    #[test]
    fn icon_path_returns_ro_path_for_image_entry() {
        assert_eq!(
            catalog().icon_path(140).as_deref(),
            Some("ro://data/texture/effect/FOO.tga")
        );
    }

    #[test]
    fn icon_path_is_none_for_name_only_entry() {
        assert_eq!(catalog().icon_path(10), None);
    }

    #[test]
    fn icon_path_is_none_for_unmapped_id() {
        assert_eq!(catalog().icon_path(9999), None);
    }

    #[test]
    fn name_returns_english_name() {
        assert_eq!(catalog().name(10), Some("Blessing"));
        assert_eq!(catalog().name(140), Some("Foo"));
    }

    #[test]
    fn name_is_none_for_unmapped_id() {
        assert_eq!(catalog().name(9999), None);
    }
}
