// This file is @generated by prost-build.
/// Wrapper around every application message. `seq` is a per-sender monotonic
/// counter used for correlation; `body` selects the concrete message. Field
/// numbers are grouped by category: 16-31 control, 32-63 client intents,
/// 64+ authoritative/world.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(uint32, tag = "1")]
    pub seq: u32,
    #[prost(
        oneof = "envelope::Body",
        tags = "16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123"
    )]
    pub body: ::core::option::Option<envelope::Body>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// 16-20: account control
        #[prost(message, tag = "16")]
        Hello(super::Hello),
        #[prost(message, tag = "17")]
        HelloAck(super::HelloAck),
        #[prost(message, tag = "18")]
        LoginRequest(super::LoginRequest),
        #[prost(message, tag = "19")]
        LoginResponse(super::LoginResponse),
        #[prost(message, tag = "20")]
        LoginFailed(super::LoginFailed),
        /// 21-31: char control
        #[prost(message, tag = "21")]
        SessionAuth(super::SessionAuth),
        #[prost(message, tag = "22")]
        CharList(super::CharList),
        #[prost(message, tag = "23")]
        CharAuthFailed(super::CharAuthFailed),
        #[prost(message, tag = "24")]
        SelectChar(super::SelectChar),
        #[prost(message, tag = "25")]
        ZoneServerInfo(super::ZoneServerInfo),
        #[prost(message, tag = "26")]
        CreateChar(super::CreateChar),
        #[prost(message, tag = "27")]
        CharCreated(super::CharCreated),
        #[prost(message, tag = "28")]
        CharCreateFailed(super::CharCreateFailed),
        #[prost(message, tag = "29")]
        DeleteCharRequest(super::DeleteCharRequest),
        #[prost(message, tag = "30")]
        DeleteCharAck(super::DeleteCharAck),
        #[prost(message, tag = "31")]
        CharListRefresh(super::CharListRefresh),
        /// 32+: zone
        #[prost(message, tag = "32")]
        MapLoaded(super::MapLoaded),
        #[prost(message, tag = "33")]
        TimeSync(super::TimeSync),
        #[prost(message, tag = "34")]
        TimeSyncAck(super::TimeSyncAck),
        #[prost(message, tag = "35")]
        EnterAck(super::EnterAck),
        #[prost(message, tag = "36")]
        MoveRequest(super::MoveRequest),
        #[prost(message, tag = "37")]
        SelfMove(super::SelfMove),
        #[prost(message, tag = "38")]
        MoveStop(super::MoveStop),
        #[prost(message, tag = "39")]
        UnitSpawn(super::UnitSpawn),
        #[prost(message, tag = "40")]
        UnitDespawn(super::UnitDespawn),
        #[prost(message, tag = "41")]
        NameRequest(super::NameRequest),
        #[prost(message, tag = "42")]
        NameResponse(super::NameResponse),
        #[prost(message, tag = "43")]
        ChatRequest(super::ChatRequest),
        #[prost(message, tag = "44")]
        ChatMessage(super::ChatMessage),
        #[prost(message, tag = "45")]
        Snapshot(super::Snapshot),
        /// 46-71: zone combat / skill / item / stat
        #[prost(message, tag = "46")]
        ActionRequest(super::ActionRequest),
        #[prost(message, tag = "47")]
        DamageDealt(super::DamageDealt),
        #[prost(message, tag = "48")]
        Knockback(super::Knockback),
        #[prost(message, tag = "49")]
        SkillCast(super::SkillCast),
        #[prost(message, tag = "50")]
        GroundSkillCast(super::GroundSkillCast),
        #[prost(message, tag = "51")]
        SkillList(super::SkillList),
        #[prost(message, tag = "52")]
        SkillDamage(super::SkillDamage),
        #[prost(message, tag = "53")]
        SkillEffect(super::SkillEffect),
        #[prost(message, tag = "54")]
        SkillCasting(super::SkillCasting),
        #[prost(message, tag = "55")]
        CastCancel(super::CastCancel),
        #[prost(message, tag = "56")]
        SkillCooldown(super::SkillCooldown),
        #[prost(message, tag = "57")]
        GroundSkill(super::GroundSkill),
        #[prost(message, tag = "58")]
        EquipItem(super::EquipItem),
        #[prost(message, tag = "59")]
        UnequipItem(super::UnequipItem),
        #[prost(message, tag = "60")]
        EquipResult(super::EquipResult),
        #[prost(message, tag = "61")]
        UnequipResult(super::UnequipResult),
        #[prost(message, tag = "62")]
        InventoryList(super::InventoryList),
        #[prost(message, tag = "63")]
        ItemAdded(super::ItemAdded),
        #[prost(message, tag = "64")]
        ItemRemoved(super::ItemRemoved),
        #[prost(message, tag = "65")]
        StatUp(super::StatUp),
        #[prost(message, tag = "66")]
        StatUpResult(super::StatUpResult),
        #[prost(message, tag = "67")]
        ParamChange(super::ParamChange),
        #[prost(message, tag = "68")]
        UnitHp(super::UnitHp),
        #[prost(message, tag = "69")]
        SpriteChange(super::SpriteChange),
        #[prost(message, tag = "70")]
        Resurrect(super::Resurrect),
        #[prost(message, tag = "71")]
        Respawn(super::Respawn),
        #[prost(message, tag = "72")]
        LearnSkill(super::LearnSkill),
        #[prost(message, tag = "73")]
        LearnSkillResult(super::LearnSkillResult),
        #[prost(message, tag = "74")]
        MapMove(super::MapMove),
        #[prost(message, tag = "75")]
        UseItem(super::UseItem),
        #[prost(message, tag = "76")]
        ItemUseResult(super::ItemUseResult),
        #[prost(message, tag = "77")]
        StatusChange(super::StatusChange),
        #[prost(message, tag = "78")]
        UnitStateChange(super::UnitStateChange),
        #[prost(message, tag = "79")]
        SpecialEffect(super::SpecialEffect),
        #[prost(message, tag = "80")]
        NpcTalk(super::NpcTalk),
        #[prost(message, tag = "81")]
        NpcDialog(super::NpcDialog),
        #[prost(message, tag = "82")]
        NpcInteract(super::NpcInteract),
        /// 83-88: cart (server->client deltas + client intents)
        #[prost(message, tag = "83")]
        CartInfo(super::CartInfo),
        #[prost(message, tag = "84")]
        CartItemAdded(super::CartItemAdded),
        #[prost(message, tag = "85")]
        CartItemRemoved(super::CartItemRemoved),
        #[prost(message, tag = "86")]
        CartMountRequest(super::CartMountRequest),
        #[prost(message, tag = "87")]
        MoveToCartRequest(super::MoveToCartRequest),
        #[prost(message, tag = "88")]
        MoveFromCartRequest(super::MoveFromCartRequest),
        /// 89-96: vending (client intents + server->client board/list/sale deltas)
        #[prost(message, tag = "89")]
        VendingOpenRequest(super::VendingOpenRequest),
        #[prost(message, tag = "90")]
        VendingCloseRequest(super::VendingCloseRequest),
        #[prost(message, tag = "91")]
        VendingListRequest(super::VendingListRequest),
        #[prost(message, tag = "92")]
        VendingPurchaseRequest(super::VendingPurchaseRequest),
        #[prost(message, tag = "93")]
        VendingBoardShown(super::VendingBoardShown),
        #[prost(message, tag = "94")]
        VendingBoardRemoved(super::VendingBoardRemoved),
        #[prost(message, tag = "95")]
        VendingList(super::VendingList),
        #[prost(message, tag = "96")]
        VendingSaleReport(super::VendingSaleReport),
        /// 97-101: npc shop (server->client window/result + client buy/sell intents)
        #[prost(message, tag = "97")]
        NpcShopOpen(super::NpcShopOpen),
        #[prost(message, tag = "98")]
        NpcBuyRequest(super::NpcBuyRequest),
        #[prost(message, tag = "99")]
        NpcSellRequest(super::NpcSellRequest),
        #[prost(message, tag = "100")]
        NpcBuyResult(super::NpcBuyResult),
        #[prost(message, tag = "101")]
        NpcSellResult(super::NpcSellResult),
        /// 102-105: item drops (server->client ground spawn/vanish + client pickup intent/result)
        #[prost(message, tag = "102")]
        ItemOnGround(super::ItemOnGround),
        #[prost(message, tag = "103")]
        ItemVanished(super::ItemVanished),
        #[prost(message, tag = "104")]
        PickupItemRequest(super::PickupItemRequest),
        #[prost(message, tag = "105")]
        PickupResult(super::PickupResult),
        /// 106-116: party
        #[prost(message, tag = "106")]
        PartyCreateRequest(super::PartyCreateRequest),
        #[prost(message, tag = "107")]
        PartyInviteRequest(super::PartyInviteRequest),
        #[prost(message, tag = "108")]
        PartyInviteNotify(super::PartyInviteNotify),
        #[prost(message, tag = "109")]
        PartyInviteResponse(super::PartyInviteResponse),
        #[prost(message, tag = "110")]
        PartyLeaveRequest(super::PartyLeaveRequest),
        #[prost(message, tag = "111")]
        PartyKickRequest(super::PartyKickRequest),
        #[prost(message, tag = "112")]
        PartyOptionsRequest(super::PartyOptionsRequest),
        #[prost(message, tag = "113")]
        PartyLeaderRequest(super::PartyLeaderRequest),
        #[prost(message, tag = "114")]
        PartyActionResult(super::PartyActionResult),
        #[prost(message, tag = "115")]
        PartyInfo(super::PartyInfo),
        #[prost(message, tag = "116")]
        PartyDisbanded(super::PartyDisbanded),
        /// 117-123: storage (server->client window/deltas/result + client deposit/withdraw/close intents)
        #[prost(message, tag = "117")]
        StorageOpened(super::StorageOpened),
        #[prost(message, tag = "118")]
        StorageDepositRequest(super::StorageDepositRequest),
        #[prost(message, tag = "119")]
        StorageWithdrawRequest(super::StorageWithdrawRequest),
        #[prost(message, tag = "120")]
        StorageCloseRequest(super::StorageCloseRequest),
        #[prost(message, tag = "121")]
        StorageItemAdded(super::StorageItemAdded),
        #[prost(message, tag = "122")]
        StorageItemRemoved(super::StorageItemRemoved),
        #[prost(message, tag = "123")]
        StorageResult(super::StorageResult),
    }
}
/// Client -> server, first message on the Control channel after connect.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub build: ::prost::alloc::string::String,
}
/// Server -> client, response to Hello.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HelloAck {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
}
/// Client -> server, account login request (replaces RO CA_LOGIN).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub client_version: u32,
}
/// One available character server, included in a successful LoginResponse.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharServerInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
    #[prost(uint32, tag = "4")]
    pub user_count: u32,
    #[prost(uint32, tag = "5")]
    pub server_type: u32,
    #[prost(bool, tag = "6")]
    pub is_new: bool,
}
/// Server -> client, successful login (replaces RO AC_ACCEPT_LOGIN).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(uint32, tag = "1")]
    pub account_id: u32,
    #[prost(uint32, tag = "2")]
    pub login_id1: u32,
    #[prost(uint32, tag = "3")]
    pub login_id2: u32,
    #[prost(uint32, tag = "4")]
    pub sex: u32,
    #[prost(string, tag = "5")]
    pub auth_token: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub char_servers: ::prost::alloc::vec::Vec<CharServerInfo>,
}
/// Server -> client, rejected login (replaces RO AC_REFUSE_LOGIN).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginFailed {
    #[prost(uint32, tag = "1")]
    pub reason_code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Client -> server, authenticate an existing Horde session on char/zone entry.
/// `char_id` is unused by the char server but reserved for zone reuse.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SessionAuth {
    #[prost(uint32, tag = "1")]
    pub account_id: u32,
    #[prost(uint32, tag = "2")]
    pub login_id1: u32,
    #[prost(uint32, tag = "3")]
    pub login_id2: u32,
    #[prost(uint32, tag = "4")]
    pub sex: u32,
    #[prost(uint32, tag = "5")]
    pub char_id: u32,
    /// Single-use handoff token issued by the char server in ZoneServerInfo.auth_token.
    /// Required by the zone server to prove the client passed character selection;
    /// unused on the char-server entry path.
    #[prost(bytes = "vec", tag = "6")]
    pub zone_auth_token: ::prost::alloc::vec::Vec<u8>,
}
/// A single character's full state (protobuf analogue of the legacy 175-byte CharacterInfo).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Character {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub class: u32,
    #[prost(uint32, tag = "4")]
    pub base_level: u32,
    #[prost(uint32, tag = "5")]
    pub job_level: u32,
    #[prost(uint64, tag = "6")]
    pub base_exp: u64,
    #[prost(uint64, tag = "7")]
    pub job_exp: u64,
    #[prost(uint32, tag = "8")]
    pub zeny: u32,
    #[prost(uint64, tag = "9")]
    pub hp: u64,
    #[prost(uint64, tag = "10")]
    pub max_hp: u64,
    #[prost(uint64, tag = "11")]
    pub sp: u64,
    #[prost(uint64, tag = "12")]
    pub max_sp: u64,
    #[prost(uint32, tag = "13")]
    pub str: u32,
    #[prost(uint32, tag = "14")]
    pub agi: u32,
    #[prost(uint32, tag = "15")]
    pub vit: u32,
    #[prost(uint32, tag = "16")]
    pub int: u32,
    #[prost(uint32, tag = "17")]
    pub dex: u32,
    #[prost(uint32, tag = "18")]
    pub luk: u32,
    #[prost(uint32, tag = "19")]
    pub status_point: u32,
    #[prost(uint32, tag = "20")]
    pub skill_point: u32,
    #[prost(uint32, tag = "21")]
    pub hair: u32,
    #[prost(uint32, tag = "22")]
    pub hair_color: u32,
    #[prost(uint32, tag = "23")]
    pub clothes_color: u32,
    #[prost(uint32, tag = "24")]
    pub weapon: u32,
    #[prost(uint32, tag = "25")]
    pub shield: u32,
    #[prost(uint32, tag = "26")]
    pub head_top: u32,
    #[prost(uint32, tag = "27")]
    pub head_mid: u32,
    #[prost(uint32, tag = "28")]
    pub head_bottom: u32,
    #[prost(uint32, tag = "29")]
    pub robe: u32,
    #[prost(uint32, tag = "30")]
    pub char_num: u32,
    #[prost(string, tag = "31")]
    pub last_map: ::prost::alloc::string::String,
    #[prost(uint32, tag = "32")]
    pub sex: u32,
    #[prost(uint32, tag = "33")]
    pub option: u32,
    #[prost(uint32, tag = "34")]
    pub karma: u32,
    #[prost(uint32, tag = "35")]
    pub manner: u32,
    #[prost(uint32, tag = "36")]
    pub rename: u32,
    #[prost(uint64, tag = "37")]
    pub delete_date: u64,
}
/// Server -> client, full character list response (replaces the legacy multi-packet char-list).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharList {
    #[prost(uint32, tag = "1")]
    pub account_id: u32,
    #[prost(uint32, tag = "2")]
    pub normal_slots: u32,
    #[prost(uint32, tag = "3")]
    pub premium_slots: u32,
    #[prost(uint32, tag = "4")]
    pub billing_slots: u32,
    #[prost(uint32, tag = "5")]
    pub producible_slots: u32,
    #[prost(uint32, tag = "6")]
    pub valid_slots: u32,
    #[prost(message, repeated, tag = "7")]
    pub characters: ::prost::alloc::vec::Vec<Character>,
    #[prost(uint32, tag = "8")]
    pub page_count: u32,
    #[prost(bool, tag = "9")]
    pub pincode_enabled: bool,
}
/// Server -> client, rejected session authentication on the char server.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharAuthFailed {
    #[prost(uint32, tag = "1")]
    pub reason: u32,
}
/// Client -> server, select a character by slot (replaces RO CH_SELECT_CHAR).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectChar {
    #[prost(uint32, tag = "1")]
    pub slot: u32,
}
/// Server -> client, zone server to connect to after selecting a character.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ZoneServerInfo {
    #[prost(uint32, tag = "1")]
    pub char_id: u32,
    #[prost(string, tag = "2")]
    pub map_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub port: u32,
    /// Single-use token the client must echo back in SessionAuth.zone_auth_token
    /// when connecting to this zone server.
    #[prost(bytes = "vec", tag = "5")]
    pub auth_token: ::prost::alloc::vec::Vec<u8>,
}
/// Client -> server, create a new character (replaces RO CH_MAKE_CHAR_V2).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateChar {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub slot: u32,
    #[prost(uint32, tag = "3")]
    pub hair_color: u32,
    #[prost(uint32, tag = "4")]
    pub hair_style: u32,
    #[prost(uint32, tag = "5")]
    pub starting_job: u32,
    #[prost(uint32, tag = "6")]
    pub sex: u32,
}
/// Server -> client, newly created character data.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharCreated {
    #[prost(message, optional, tag = "1")]
    pub character: ::core::option::Option<Character>,
}
/// Server -> client, character creation failed.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharCreateFailed {
    #[prost(uint32, tag = "1")]
    pub reason_code: u32,
}
/// Client -> server, request character deletion (replaces RO CH_REQ_CHAR_DELETE2).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteCharRequest {
    #[prost(uint32, tag = "1")]
    pub char_id: u32,
}
/// Server -> client, acknowledgement of a deletion request.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteCharAck {
    #[prost(uint32, tag = "1")]
    pub char_id: u32,
    #[prost(uint32, tag = "2")]
    pub result: u32,
    #[prost(uint64, tag = "3")]
    pub delete_date: u64,
}
/// Client -> server, request a fresh character list (replaces RO CH_CHARLIST_REQ).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharListRefresh {}
/// Client -> server, the map finished loading; spawn me (replaces RO CZ_NOTIFY_ACTORINIT 0x007D).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MapLoaded {}
/// Client -> server, client clock for time sync (replaces RO CZ_REQUEST_TIME/TIME2).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeSync {
    #[prost(uint32, tag = "1")]
    pub client_tick: u32,
}
/// Server -> client, authoritative clock reply (replaces RO ZC_NOTIFY_TIME/TIME2).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimeSyncAck {
    #[prost(uint32, tag = "1")]
    pub server_tick: u32,
}
/// Server -> client, accept zone entry (replaces RO ZC_ACCEPT_ENTER 0x02EB + ZC_AID 0x0283).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnterAck {
    #[prost(uint32, tag = "1")]
    pub account_id: u32,
    #[prost(uint32, tag = "2")]
    pub x: u32,
    #[prost(uint32, tag = "3")]
    pub y: u32,
    #[prost(uint32, tag = "4")]
    pub dir: u32,
    #[prost(uint64, tag = "5")]
    pub start_time: u64,
    #[prost(uint32, tag = "6")]
    pub font: u32,
}
/// Server -> client, load a different map and reposition there (replaces RO
/// ZC_NPCACK_MAPMOVE 0x0091). The client unloads the current map, loads
/// `map_name`, places the character at (x, y), and re-sends MapLoaded.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MapMove {
    #[prost(string, tag = "1")]
    pub map_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub x: u32,
    #[prost(uint32, tag = "3")]
    pub y: u32,
}
/// Client -> server, request to move to a destination cell (replaces RO CZ_REQUEST_MOVE2 0x035F).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoveRequest {
    #[prost(uint32, tag = "1")]
    pub dest_x: u32,
    #[prost(uint32, tag = "2")]
    pub dest_y: u32,
}
/// Server -> client, own-character authoritative movement (replaces RO ZC_NOTIFY_PLAYERMOVE 0x0087).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelfMove {
    #[prost(uint32, tag = "1")]
    pub src_x: u32,
    #[prost(uint32, tag = "2")]
    pub src_y: u32,
    #[prost(uint32, tag = "3")]
    pub dst_x: u32,
    #[prost(uint32, tag = "4")]
    pub dst_y: u32,
    #[prost(uint64, tag = "5")]
    pub start_time: u64,
}
/// Server -> client, an entity stopped moving (replaces RO ZC_NOTIFY_MOVE_STOP 0x0088).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoveStop {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(uint32, tag = "2")]
    pub x: u32,
    #[prost(uint32, tag = "3")]
    pub y: u32,
}
/// Server -> client, an entity entered view (collapses RO ZC_NOTIFY_NEWENTRY 0x09FE,
/// ZC_NOTIFY_STANDENTRY 0x09FF and ZC_NOTIFY_MOVEENTRY 0x09FD). The `moving`, `dst_*` and
/// `move_start_time` fields carry the moveentry case.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnitSpawn {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(uint32, tag = "2")]
    pub aid: u32,
    #[prost(uint32, tag = "3")]
    pub object_type: u32,
    #[prost(uint32, tag = "4")]
    pub job: u32,
    #[prost(uint32, tag = "5")]
    pub x: u32,
    #[prost(uint32, tag = "6")]
    pub y: u32,
    #[prost(uint32, tag = "7")]
    pub dir: u32,
    #[prost(uint32, tag = "8")]
    pub speed: u32,
    #[prost(uint32, tag = "9")]
    pub hp: u32,
    #[prost(uint32, tag = "10")]
    pub max_hp: u32,
    #[prost(uint32, tag = "11")]
    pub clevel: u32,
    #[prost(uint32, tag = "12")]
    pub body_state: u32,
    #[prost(uint32, tag = "13")]
    pub health_state: u32,
    #[prost(uint32, tag = "14")]
    pub effect_state: u32,
    #[prost(uint32, tag = "15")]
    pub head: u32,
    #[prost(uint32, tag = "16")]
    pub weapon: u32,
    #[prost(uint32, tag = "17")]
    pub shield: u32,
    #[prost(uint32, tag = "18")]
    pub accessory: u32,
    #[prost(uint32, tag = "19")]
    pub accessory2: u32,
    #[prost(uint32, tag = "20")]
    pub accessory3: u32,
    #[prost(uint32, tag = "21")]
    pub head_palette: u32,
    #[prost(uint32, tag = "22")]
    pub body_palette: u32,
    #[prost(uint32, tag = "23")]
    pub head_dir: u32,
    #[prost(uint32, tag = "24")]
    pub robe: u32,
    #[prost(uint32, tag = "25")]
    pub guild_id: u32,
    #[prost(uint32, tag = "26")]
    pub sex: u32,
    #[prost(bool, tag = "27")]
    pub is_boss: bool,
    #[prost(string, tag = "28")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "29")]
    pub moving: bool,
    #[prost(uint32, tag = "30")]
    pub dst_x: u32,
    #[prost(uint32, tag = "31")]
    pub dst_y: u32,
    #[prost(uint64, tag = "32")]
    pub move_start_time: u64,
    #[prost(uint32, tag = "33")]
    pub virtue: u32,
}
/// Server -> client, an entity left view (replaces RO ZC_NOTIFY_VANISH 0x0080).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnitDespawn {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(uint32, tag = "2")]
    pub reason: u32,
}
/// EFST icon bar — apply (on=true) / remove (on=false).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusChange {
    /// target AID/GID
    #[prost(uint32, tag = "1")]
    pub unit_id: u32,
    /// rAthena EFST id
    #[prost(uint32, tag = "2")]
    pub efst: u32,
    #[prost(bool, tag = "3")]
    pub on: bool,
    /// 0 = infinite
    #[prost(uint32, tag = "4")]
    pub total_ms: u32,
    /// 0 = infinite
    #[prost(uint32, tag = "5")]
    pub remain_ms: u32,
    #[prost(int32, tag = "6")]
    pub val1: i32,
    #[prost(int32, tag = "7")]
    pub val2: i32,
    #[prost(int32, tag = "8")]
    pub val3: i32,
}
/// Sprite ailment state — the unit's aggregate opt fields.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnitStateChange {
    #[prost(uint32, tag = "1")]
    pub unit_id: u32,
    /// opt1  (single-valued)
    #[prost(uint32, tag = "2")]
    pub body_state: u32,
    /// opt2  (bitmask)
    #[prost(uint32, tag = "3")]
    pub health_state: u32,
    /// option (bitmask)
    #[prost(uint32, tag = "4")]
    pub effect_state: u32,
    /// opt3  (bitmask)
    #[prost(uint32, tag = "5")]
    pub virtue: u32,
}
/// One-shot effect — fire and forget.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpecialEffect {
    #[prost(uint32, tag = "1")]
    pub source_id: u32,
    /// rAthena EF_* id
    #[prost(uint32, tag = "2")]
    pub effect_id: u32,
}
/// Client -> server, request an entity's name (replaces RO CZ_REQNAME2 0x0368).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NameRequest {
    #[prost(uint32, tag = "1")]
    pub entity_id: u32,
}
/// Server -> client, an entity's name (replaces RO ZC_ACK_REQNAME 0x0095 + ZC_ACK_REQNAMEALL 0x0195).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NameResponse {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub party_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub guild_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub position_name: ::prost::alloc::string::String,
}
/// Client -> server, public chat message (replaces RO CZ_REQUEST_CHAT 0x008C).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatRequest {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Server -> client, an entity's chat message (replaces RO ZC_NOTIFY_CHAT 0x008D).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatMessage {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// One entity's position/state within a Snapshot.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SnapshotEntity {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(uint32, tag = "2")]
    pub x: u32,
    #[prost(uint32, tag = "3")]
    pub y: u32,
    #[prost(uint32, tag = "4")]
    pub dir: u32,
    #[prost(uint32, tag = "5")]
    pub move_state: u32,
    #[prost(uint32, tag = "6")]
    pub hp_pct: u32,
}
/// Server -> client, full-state AoI snapshot (rides ChannelId 4 / Unreliable; design Part 5).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Snapshot {
    #[prost(uint64, tag = "1")]
    pub server_tick: u64,
    #[prost(message, repeated, tag = "2")]
    pub entities: ::prost::alloc::vec::Vec<SnapshotEntity>,
}
/// Client -> server, request a basic action against a target (replaces RO CZ_REQUEST_ACT 0x0437).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActionRequest {
    #[prost(uint32, tag = "1")]
    pub target_id: u32,
    #[prost(uint32, tag = "2")]
    pub action: u32,
}
/// Server -> client, basic-attack damage result (replaces RO ZC_NOTIFY_ACT 0x08C8).
/// `damage`/`damage2` are signed so negative (heal-as-damage) values survive.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DamageDealt {
    #[prost(uint32, tag = "1")]
    pub src_id: u32,
    #[prost(uint32, tag = "2")]
    pub target_id: u32,
    #[prost(uint64, tag = "3")]
    pub server_tick: u64,
    #[prost(uint32, tag = "4")]
    pub src_speed: u32,
    #[prost(uint32, tag = "5")]
    pub dmg_speed: u32,
    #[prost(sint32, tag = "6")]
    pub damage: i32,
    #[prost(uint32, tag = "7")]
    pub div: u32,
    #[prost(uint32, tag = "8")]
    pub r#type: u32,
    #[prost(sint32, tag = "9")]
    pub damage2: i32,
    #[prost(bool, tag = "10")]
    pub is_sp_damage: bool,
}
/// Server -> client, an entity was knocked back (replaces RO ZC_BLOWNBACK 0x01B1).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Knockback {
    #[prost(uint32, tag = "1")]
    pub unit_id: u32,
    #[prost(uint32, tag = "2")]
    pub dst_x: u32,
    #[prost(uint32, tag = "3")]
    pub dst_y: u32,
}
/// Client -> server, cast a skill at a target (replaces RO CZ_USE_SKILL 0x0113).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillCast {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub level: u32,
    #[prost(uint32, tag = "3")]
    pub target_id: u32,
}
/// Client -> server, cast a ground-targeted skill (replaces RO CZ_USE_SKILL_TOGROUND 0x0AF4).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroundSkillCast {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub level: u32,
    #[prost(uint32, tag = "3")]
    pub x: u32,
    #[prost(uint32, tag = "4")]
    pub y: u32,
}
/// A prerequisite skill + level needed to learn a SkillInfo entry.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillRequirement {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub level: u32,
}
/// One skill within a SkillList; carries the full available-tree view.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillInfo {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub r#type: u32,
    #[prost(uint32, tag = "3")]
    pub level: u32,
    #[prost(uint32, tag = "4")]
    pub sp: u32,
    #[prost(uint32, tag = "5")]
    pub range: u32,
    #[prost(string, tag = "6")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub upgradable: bool,
    #[prost(uint32, tag = "8")]
    pub max_level: u32,
    #[prost(message, repeated, tag = "9")]
    pub requires: ::prost::alloc::vec::Vec<SkillRequirement>,
    #[prost(uint32, tag = "10")]
    pub req_base_level: u32,
    #[prost(uint32, tag = "11")]
    pub req_job_level: u32,
    #[prost(uint32, tag = "12")]
    pub job_id: u32,
}
/// Client -> server, spend one skill point to learn/raise a skill (replaces RO CZ_UPGRADE_SKILLLEVEL 0x0112).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LearnSkill {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
}
/// Server -> client, result of a learn attempt; reason 0 = ok, else the SkillTree reject-reason code.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LearnSkillResult {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(uint32, tag = "3")]
    pub reason: u32,
}
/// Server -> client, the full learned-skill list (replaces RO ZC_SKILLINFO_LIST 0x010F).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillList {
    #[prost(message, repeated, tag = "1")]
    pub skills: ::prost::alloc::vec::Vec<SkillInfo>,
}
/// Server -> client, skill damage result (replaces RO ZC_NOTIFY_SKILL 0x01DE).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillDamage {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub level: u32,
    #[prost(uint32, tag = "3")]
    pub src_id: u32,
    #[prost(uint32, tag = "4")]
    pub target_id: u32,
    #[prost(uint64, tag = "5")]
    pub server_tick: u64,
    #[prost(sint32, tag = "6")]
    pub damage: i32,
    #[prost(uint32, tag = "7")]
    pub div: u32,
    #[prost(uint32, tag = "8")]
    pub r#type: u32,
    #[prost(uint32, tag = "9")]
    pub src_delay: u32,
    #[prost(uint32, tag = "10")]
    pub dst_delay: u32,
}
/// Server -> client, no-damage skill effect (replaces RO ZC_USE_SKILL 0x011A).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillEffect {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub level: u32,
    #[prost(uint32, tag = "3")]
    pub src_id: u32,
    #[prost(uint32, tag = "4")]
    pub target_id: u32,
    #[prost(uint32, tag = "5")]
    pub result: u32,
}
/// Server -> client, a skill cast bar started (replaces RO ZC_USE_SKILL2 0x0B1A).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillCasting {
    #[prost(uint32, tag = "1")]
    pub src_id: u32,
    #[prost(uint32, tag = "2")]
    pub target_id: u32,
    #[prost(uint32, tag = "3")]
    pub x: u32,
    #[prost(uint32, tag = "4")]
    pub y: u32,
    #[prost(uint32, tag = "5")]
    pub skill_id: u32,
    #[prost(uint32, tag = "6")]
    pub property: u32,
    #[prost(uint32, tag = "7")]
    pub cast_time: u32,
}
/// Server -> client, a skill cast was cancelled (replaces RO ZC_NOTIFY_CAST_CANCEL 0x01B9).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CastCancel {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
}
/// Server -> client, a skill went on cooldown (replaces RO ZC_SKILL_POSTDELAY 0x043D).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillCooldown {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub tick: u32,
}
/// Server -> client, a ground-targeted skill landed (replaces RO ZC_NOTIFY_GROUNDSKILL 0x0117).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GroundSkill {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub src_id: u32,
    #[prost(uint32, tag = "3")]
    pub level: u32,
    #[prost(uint32, tag = "4")]
    pub x: u32,
    #[prost(uint32, tag = "5")]
    pub y: u32,
    #[prost(uint64, tag = "6")]
    pub server_tick: u64,
}
/// Client -> server, equip an inventory item (replaces RO CZ_REQ_WEAR_EQUIP 0x0998).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EquipItem {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub position: u32,
}
/// Client -> server, take off an equipped item (replaces RO CZ_REQ_TAKEOFF_EQUIP 0x00AB).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnequipItem {
    #[prost(uint32, tag = "1")]
    pub index: u32,
}
/// Server -> client, result of an equip request (replaces RO ZC_ACK_WEAR_EQUIP 0x0999).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EquipResult {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub wear_location: u32,
    #[prost(uint32, tag = "3")]
    pub view_id: u32,
    #[prost(uint32, tag = "4")]
    pub result: u32,
}
/// Server -> client, result of an unequip request (replaces RO ZC_ACK_TAKEOFF_EQUIP 0x099A).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnequipResult {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub wear_location: u32,
    #[prost(uint32, tag = "3")]
    pub result: u32,
}
/// One inventory slot within an InventoryList.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InventoryItem {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub nameid: u32,
    #[prost(uint32, tag = "3")]
    pub r#type: u32,
    #[prost(uint32, tag = "4")]
    pub amount: u32,
    #[prost(uint32, tag = "5")]
    pub location: u32,
    #[prost(bool, tag = "6")]
    pub identified: bool,
    #[prost(uint32, tag = "7")]
    pub attribute: u32,
    #[prost(uint32, tag = "8")]
    pub refine: u32,
    #[prost(uint32, repeated, tag = "9")]
    pub cards: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint64, tag = "10")]
    pub expire_time: u64,
    #[prost(uint32, tag = "11")]
    pub bind_on_equip: u32,
    #[prost(bool, tag = "12")]
    pub favorite: bool,
    #[prost(uint32, tag = "13")]
    pub look: u32,
}
/// Server -> client, the full inventory dump (collapses RO ZC_INVENTORY_START/
/// ITEMLIST_NORMAL/ITEMLIST_EQUIP/END 0x0B08-0x0B0B).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryList {
    #[prost(message, repeated, tag = "1")]
    pub normal: ::prost::alloc::vec::Vec<InventoryItem>,
    #[prost(message, repeated, tag = "2")]
    pub equip: ::prost::alloc::vec::Vec<InventoryItem>,
}
/// Server -> client, an item was added to the inventory (replaces RO ZC_ITEM_PICKUP_ACK 0x0A37).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemAdded {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub nameid: u32,
    #[prost(bool, tag = "4")]
    pub identified: bool,
    #[prost(uint32, tag = "5")]
    pub attribute: u32,
    #[prost(uint32, tag = "6")]
    pub refine: u32,
    #[prost(uint32, repeated, tag = "7")]
    pub cards: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "8")]
    pub location: u32,
    #[prost(uint32, tag = "9")]
    pub r#type: u32,
    #[prost(uint32, tag = "10")]
    pub result: u32,
    #[prost(uint64, tag = "11")]
    pub expire_time: u64,
    #[prost(uint32, tag = "12")]
    pub look: u32,
}
/// Server -> client, an item was removed from the inventory (replaces RO ZC_DELETE_ITEM_FROM_BODY 0x07FA).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemRemoved {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub reason: u32,
}
/// Server -> client, the full cart dump (sent on mount/login). Mirrors InventoryList
/// but for the separate cart container.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CartInfo {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<InventoryItem>,
}
/// Server -> client, an item was added to the cart. Mirrors ItemAdded.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CartItemAdded {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub nameid: u32,
    #[prost(bool, tag = "4")]
    pub identified: bool,
    #[prost(uint32, tag = "5")]
    pub attribute: u32,
    #[prost(uint32, tag = "6")]
    pub refine: u32,
    #[prost(uint32, repeated, tag = "7")]
    pub cards: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "8")]
    pub location: u32,
    #[prost(uint32, tag = "9")]
    pub r#type: u32,
    #[prost(uint32, tag = "10")]
    pub result: u32,
    #[prost(uint64, tag = "11")]
    pub expire_time: u64,
    #[prost(uint32, tag = "12")]
    pub look: u32,
}
/// Server -> client, an item was removed from the cart. Mirrors ItemRemoved.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CartItemRemoved {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub reason: u32,
}
/// Client -> server, mount (true) or unmount (false) the cart. Gated on Pushcart learned.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CartMountRequest {
    #[prost(bool, tag = "1")]
    pub mount: bool,
}
/// Client -> server, move an inventory item into the cart.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoveToCartRequest {
    #[prost(uint32, tag = "1")]
    pub inventory_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, move a cart item back into the inventory.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MoveFromCartRequest {
    #[prost(uint32, tag = "1")]
    pub cart_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// One line of a vending shop the merchant wants to open: a cart slot, how many
/// to sell, and the per-unit price.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingEntry {
    #[prost(uint32, tag = "1")]
    pub cart_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub price: u32,
}
/// Client -> server, open a vending shop selling the given cart items under a title.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VendingOpenRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<VendingEntry>,
}
/// Client -> server, close the player's own vending shop.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingCloseRequest {}
/// Client -> server, request the item list of a nearby vendor's shop.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingListRequest {
    #[prost(uint64, tag = "1")]
    pub vendor_unit_id: u64,
}
/// One line of a buy request: which shop entry and how many units to buy.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingBuy {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, buy items from a vendor's shop.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VendingPurchaseRequest {
    #[prost(uint64, tag = "1")]
    pub vendor_unit_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<VendingBuy>,
}
/// Server -> client, a vending shop board appeared over a merchant (area broadcast / on view enter).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingBoardShown {
    #[prost(uint64, tag = "1")]
    pub unit_id: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
}
/// Server -> client, a vending shop board was removed (close / sold out / out of view).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingBoardRemoved {
    #[prost(uint64, tag = "1")]
    pub unit_id: u64,
}
/// One item on display in a vending shop. Mirrors InventoryItem's display fields plus a price.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingShopItem {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub nameid: u32,
    #[prost(uint32, tag = "3")]
    pub r#type: u32,
    #[prost(uint32, tag = "4")]
    pub amount: u32,
    #[prost(bool, tag = "5")]
    pub identified: bool,
    #[prost(uint32, tag = "6")]
    pub attribute: u32,
    #[prost(uint32, tag = "7")]
    pub refine: u32,
    #[prost(uint32, repeated, tag = "8")]
    pub cards: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "9")]
    pub price: u32,
}
/// Server -> client, the full item list of a vendor's shop (reply to VendingListRequest).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VendingList {
    #[prost(uint64, tag = "1")]
    pub vendor_unit_id: u64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<VendingShopItem>,
}
/// Server -> client (seller), a unit of the shop was sold.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VendingSaleReport {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub nameid: u32,
    #[prost(uint32, tag = "3")]
    pub amount: u32,
    #[prost(uint32, tag = "4")]
    pub zeny_gained: u32,
    #[prost(string, tag = "5")]
    pub buyer_name: ::prost::alloc::string::String,
}
/// One item the NPC shop sells, shown in the buy window at its buy price.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcShopBuyItem {
    #[prost(uint32, tag = "1")]
    pub nameid: u32,
    #[prost(uint32, tag = "2")]
    pub r#type: u32,
    #[prost(uint32, tag = "3")]
    pub price: u32,
}
/// One sellable inventory slot, shown in the sell window at its server-computed sell price.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcShopSellItem {
    #[prost(uint32, tag = "1")]
    pub inventory_index: u32,
    #[prost(uint32, tag = "2")]
    pub nameid: u32,
    #[prost(uint32, tag = "3")]
    pub r#type: u32,
    #[prost(uint32, tag = "4")]
    pub amount: u32,
    #[prost(uint32, tag = "5")]
    pub sell_price: u32,
}
/// Server -> client, opens the NPC shop window with both buy and sell lists computed server-side.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NpcShopOpen {
    #[prost(uint64, tag = "1")]
    pub unit_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub buy_items: ::prost::alloc::vec::Vec<NpcShopBuyItem>,
    #[prost(message, repeated, tag = "3")]
    pub sell_items: ::prost::alloc::vec::Vec<NpcShopSellItem>,
}
/// One line of a buy request: which shop item and how many units to buy.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcBuyEntry {
    #[prost(uint32, tag = "1")]
    pub nameid: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, buy items from an NPC shop.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NpcBuyRequest {
    #[prost(uint64, tag = "1")]
    pub unit_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<NpcBuyEntry>,
}
/// One line of a sell request: which inventory slot and how many units to sell.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcSellEntry {
    #[prost(uint32, tag = "1")]
    pub inventory_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, sell inventory items to an NPC shop.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NpcSellRequest {
    #[prost(uint64, tag = "1")]
    pub unit_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<NpcSellEntry>,
}
/// Server -> client, result of a buy request (ok | not_enough_zeny | overweight | no_slots | invalid | out_of_range).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcBuyResult {
    #[prost(uint32, tag = "1")]
    pub result: u32,
}
/// Server -> client, result of a sell request (ok | invalid | out_of_range).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcSellResult {
    #[prost(uint32, tag = "1")]
    pub result: u32,
}
/// Client -> server, allocate a status point to a stat (replaces RO CZ_STATUS_CHANGE 0x00BB).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatUp {
    #[prost(uint32, tag = "1")]
    pub stat_id: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Server -> client, result of a stat allocation (replaces RO ZC_STATUS_CHANGE 0x00BC).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatUpResult {
    #[prost(uint32, tag = "1")]
    pub stat_id: u32,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(uint32, tag = "3")]
    pub value: u32,
}
/// Server -> client, a parameter changed (collapses RO ZC_PAR_CHANGE 0x00B0 +
/// ZC_LONGPAR_CHANGE 0x00B1; uint64 covers both 32- and 64-bit params).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParamChange {
    #[prost(uint32, tag = "1")]
    pub var_id: u32,
    #[prost(uint64, tag = "2")]
    pub value: u64,
}
/// Server -> client, an entity's HP changed (replaces RO ZC_HP_INFO 0x0977).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnitHp {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(uint32, tag = "2")]
    pub hp: u32,
    #[prost(uint32, tag = "3")]
    pub max_hp: u32,
}
/// Server -> client, an entity's sprite changed (replaces RO ZC_SPRITE_CHANGE 0x01D7).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SpriteChange {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(uint32, tag = "2")]
    pub r#type: u32,
    #[prost(uint32, tag = "3")]
    pub val: u32,
    #[prost(uint32, tag = "4")]
    pub val2: u32,
}
/// Server -> client, an entity was resurrected (replaces RO ZC_RESURRECTION 0x0148).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Resurrect {
    #[prost(uint32, tag = "1")]
    pub gid: u32,
    #[prost(uint32, tag = "2")]
    pub r#type: u32,
}
/// Client -> server, respawn or return to char select after death (replaces RO CZ_RESTART 0x00B2).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Respawn {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
}
/// Client -> server, use a consumable item by inventory slot index (replaces RO CZ_USE_ITEM 0x00A7).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UseItem {
    #[prost(uint32, tag = "1")]
    pub index: u32,
}
/// Server -> client, result of a use-item attempt; reason 0 = ok, else the rejection code.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemUseResult {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(uint32, tag = "3")]
    pub reason: u32,
}
/// Client -> server, the player clicked an NPC unit (replaces RO CZ_CONTACTNPC 0x0090).
/// npc_id is the NPC's unit/entity id on the map.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcTalk {
    #[prost(uint32, tag = "1")]
    pub npc_id: u32,
}
/// Server -> client, one frame per dialog suspension point; the mes text accumulated
/// since the last suspension rides with it. `expect` names the input the client must
/// now collect; `options` is populated for MENU only.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcDialog {
    #[prost(uint32, tag = "1")]
    pub npc_id: u32,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(enumeration = "npc_dialog::Expect", tag = "3")]
    pub expect: i32,
    #[prost(string, repeated, tag = "4")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Nested message and enum types in `NpcDialog`.
pub mod npc_dialog {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Expect {
        Next = 0,
        Menu = 1,
        InputInt = 2,
        InputStr = 3,
        Close = 4,
    }
    impl Expect {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Next => "NEXT",
                Self::Menu => "MENU",
                Self::InputInt => "INPUT_INT",
                Self::InputStr => "INPUT_STR",
                Self::Close => "CLOSE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NEXT" => Some(Self::Next),
                "MENU" => Some(Self::Menu),
                "INPUT_INT" => Some(Self::InputInt),
                "INPUT_STR" => Some(Self::InputStr),
                "CLOSE" => Some(Self::Close),
                _ => None,
            }
        }
    }
}
/// Client -> server, the player's response to the pending NpcDialog.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NpcInteract {
    #[prost(uint32, tag = "1")]
    pub npc_id: u32,
    #[prost(oneof = "npc_interact::Response", tags = "2, 3, 4, 5, 6")]
    pub response: ::core::option::Option<npc_interact::Response>,
}
/// Nested message and enum types in `NpcInteract`.
pub mod npc_interact {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Response {
        #[prost(bool, tag = "2")]
        Continue(bool),
        #[prost(uint32, tag = "3")]
        Choice(u32),
        #[prost(sint64, tag = "4")]
        Number(i64),
        #[prost(string, tag = "5")]
        Input(::prost::alloc::string::String),
        #[prost(bool, tag = "6")]
        Cancel(bool),
    }
}
/// Server -> client, an item appeared on a map cell (drop or walk-up discovery).
/// is_falling marks a fresh drop (animated) vs an already-lying item (view-enter).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemOnGround {
    #[prost(uint64, tag = "1")]
    pub ground_id: u64,
    #[prost(uint32, tag = "2")]
    pub nameid: u32,
    #[prost(uint32, tag = "3")]
    pub amount: u32,
    #[prost(uint32, tag = "4")]
    pub x: u32,
    #[prost(uint32, tag = "5")]
    pub y: u32,
    #[prost(bool, tag = "6")]
    pub identified: bool,
    #[prost(bool, tag = "7")]
    pub is_falling: bool,
    #[prost(uint32, tag = "8")]
    pub sub_x: u32,
    #[prost(uint32, tag = "9")]
    pub sub_y: u32,
}
/// Server -> client, a ground item was removed (picked up or expired).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemVanished {
    #[prost(uint64, tag = "1")]
    pub ground_id: u64,
    #[prost(enumeration = "ItemVanishReason", tag = "2")]
    pub reason: i32,
}
/// Client -> server, request to pick up a ground item by its ground id.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PickupItemRequest {
    #[prost(uint64, tag = "1")]
    pub ground_id: u64,
}
/// Server -> client, result of a pickup request; the inventory delta rides the existing ItemAdded.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PickupResult {
    #[prost(uint64, tag = "1")]
    pub ground_id: u64,
    #[prost(enumeration = "PickupResultCode", tag = "2")]
    pub result: i32,
}
/// Client -> server, create a new party with the requester as leader.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyCreateRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// Client -> server, invite a character to the sender's party by id or by name
/// (char_id wins when both are set; name is resolved via a UnitRegistry reverse lookup).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyInviteRequest {
    #[prost(uint32, tag = "1")]
    pub target_char_id: u32,
    #[prost(string, tag = "2")]
    pub target_name: ::prost::alloc::string::String,
}
/// Server -> client, party invite notification shown to the invitee.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyInviteNotify {
    #[prost(uint32, tag = "1")]
    pub party_id: u32,
    #[prost(string, tag = "2")]
    pub party_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub inviter_name: ::prost::alloc::string::String,
}
/// Client -> server, the invitee's accept/decline response to a PartyInviteNotify.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyInviteResponse {
    #[prost(uint32, tag = "1")]
    pub party_id: u32,
    #[prost(bool, tag = "2")]
    pub accept: bool,
}
/// Client -> server, leave the sender's current party. If the sender is the
/// leader, the party disbands instead.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyLeaveRequest {}
/// Client -> server, leader-only request to remove a member from the party.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyKickRequest {
    #[prost(uint32, tag = "1")]
    pub target_char_id: u32,
}
/// Client -> server, leader-only request to toggle even-share EXP.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyOptionsRequest {
    #[prost(bool, tag = "1")]
    pub exp_share: bool,
}
/// Client -> server, leader-only request to transfer leadership to an online,
/// same-map member.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyLeaderRequest {
    #[prost(uint32, tag = "1")]
    pub target_char_id: u32,
}
/// Server -> client, acknowledgement of a party request. `action` names the
/// request being acked (e.g. "create", "invite", "kick"); `error` is
/// PartyError.NONE on success.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyActionResult {
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub success: bool,
    #[prost(enumeration = "PartyError", tag = "3")]
    pub error: i32,
}
/// One member entry within a PartyInfo snapshot.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyMember {
    #[prost(uint32, tag = "1")]
    pub char_id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub base_level: u32,
    #[prost(bool, tag = "4")]
    pub online: bool,
    #[prost(string, tag = "5")]
    pub map: ::prost::alloc::string::String,
}
/// Server -> client, full party snapshot sent on any membership or option change.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartyInfo {
    #[prost(uint32, tag = "1")]
    pub party_id: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub leader_char_id: u32,
    #[prost(bool, tag = "4")]
    pub exp_share: bool,
    #[prost(message, repeated, tag = "5")]
    pub members: ::prost::alloc::vec::Vec<PartyMember>,
}
/// Server -> client, the party was disbanded (leader left, or the last member left).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartyDisbanded {
    #[prost(uint32, tag = "1")]
    pub party_id: u32,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// Server -> client, the full storage dump (sent on open). Mirrors CartInfo.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageOpened {
    #[prost(uint32, tag = "1")]
    pub capacity: u32,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<InventoryItem>,
}
/// Client -> server, move an inventory item into storage.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageDepositRequest {
    #[prost(uint32, tag = "1")]
    pub inventory_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, move a storage item back into the inventory.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageWithdrawRequest {
    #[prost(uint32, tag = "1")]
    pub storage_index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
}
/// Client -> server, close the currently open storage window.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageCloseRequest {}
/// Server -> client, an item was added to storage. Mirrors CartItemAdded.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageItemAdded {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub nameid: u32,
    #[prost(bool, tag = "4")]
    pub identified: bool,
    #[prost(uint32, tag = "5")]
    pub attribute: u32,
    #[prost(uint32, tag = "6")]
    pub refine: u32,
    #[prost(uint32, repeated, tag = "7")]
    pub cards: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "8")]
    pub location: u32,
    #[prost(uint32, tag = "9")]
    pub r#type: u32,
    #[prost(uint32, tag = "10")]
    pub result: u32,
    #[prost(uint64, tag = "11")]
    pub expire_time: u64,
    #[prost(uint32, tag = "12")]
    pub look: u32,
}
/// Server -> client, an item was removed from storage. Mirrors CartItemRemoved.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageItemRemoved {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint32, tag = "2")]
    pub amount: u32,
    #[prost(uint32, tag = "3")]
    pub reason: u32,
}
/// Server -> client, result of a storage deposit/withdraw/open request.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageResult {
    #[prost(enumeration = "StorageResultCode", tag = "1")]
    pub result: i32,
}
/// Why a ground item disappeared.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ItemVanishReason {
    PickedUp = 0,
    Expired = 1,
}
impl ItemVanishReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PickedUp => "PICKED_UP",
            Self::Expired => "EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PICKED_UP" => Some(Self::PickedUp),
            "EXPIRED" => Some(Self::Expired),
            _ => None,
        }
    }
}
/// Outcome of a pickup request.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PickupResultCode {
    Ok = 0,
    TooFar = 1,
    Overweight = 2,
    InventoryFull = 3,
    Gone = 4,
    Failed = 5,
}
impl PickupResultCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::TooFar => "TOO_FAR",
            Self::Overweight => "OVERWEIGHT",
            Self::InventoryFull => "INVENTORY_FULL",
            Self::Gone => "GONE",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK" => Some(Self::Ok),
            "TOO_FAR" => Some(Self::TooFar),
            "OVERWEIGHT" => Some(Self::Overweight),
            "INVENTORY_FULL" => Some(Self::InventoryFull),
            "GONE" => Some(Self::Gone),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Reason a party request failed; NONE means it succeeded.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PartyError {
    None = 0,
    NameTaken = 1,
    AlreadyInParty = 2,
    PartyFull = 3,
    NotLeader = 4,
    LevelRange = 5,
    SameAccount = 6,
    TargetOffline = 7,
    NotMember = 8,
    NotSameMap = 9,
}
impl PartyError {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::NameTaken => "NAME_TAKEN",
            Self::AlreadyInParty => "ALREADY_IN_PARTY",
            Self::PartyFull => "PARTY_FULL",
            Self::NotLeader => "NOT_LEADER",
            Self::LevelRange => "LEVEL_RANGE",
            Self::SameAccount => "SAME_ACCOUNT",
            Self::TargetOffline => "TARGET_OFFLINE",
            Self::NotMember => "NOT_MEMBER",
            Self::NotSameMap => "NOT_SAME_MAP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "NAME_TAKEN" => Some(Self::NameTaken),
            "ALREADY_IN_PARTY" => Some(Self::AlreadyInParty),
            "PARTY_FULL" => Some(Self::PartyFull),
            "NOT_LEADER" => Some(Self::NotLeader),
            "LEVEL_RANGE" => Some(Self::LevelRange),
            "SAME_ACCOUNT" => Some(Self::SameAccount),
            "TARGET_OFFLINE" => Some(Self::TargetOffline),
            "NOT_MEMBER" => Some(Self::NotMember),
            "NOT_SAME_MAP" => Some(Self::NotSameMap),
            _ => None,
        }
    }
}
/// Outcome of a storage deposit/withdraw/open request. Values are prefixed
/// because proto3 enum constants share the package namespace (C++ scoping
/// rules), and OK/INVENTORY_FULL/OVERWEIGHT already exist on PickupResultCode.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StorageResultCode {
    StorageOk = 0,
    StorageFull = 1,
    StorageInventoryFull = 2,
    StorageOverweight = 3,
    StorageNotStorable = 4,
    StorageItemEquipped = 5,
    StorageInvalidAmount = 6,
    StorageNotOpen = 7,
    StorageBasicSkillRequired = 8,
}
impl StorageResultCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StorageOk => "STORAGE_OK",
            Self::StorageFull => "STORAGE_FULL",
            Self::StorageInventoryFull => "STORAGE_INVENTORY_FULL",
            Self::StorageOverweight => "STORAGE_OVERWEIGHT",
            Self::StorageNotStorable => "STORAGE_NOT_STORABLE",
            Self::StorageItemEquipped => "STORAGE_ITEM_EQUIPPED",
            Self::StorageInvalidAmount => "STORAGE_INVALID_AMOUNT",
            Self::StorageNotOpen => "STORAGE_NOT_OPEN",
            Self::StorageBasicSkillRequired => "STORAGE_BASIC_SKILL_REQUIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STORAGE_OK" => Some(Self::StorageOk),
            "STORAGE_FULL" => Some(Self::StorageFull),
            "STORAGE_INVENTORY_FULL" => Some(Self::StorageInventoryFull),
            "STORAGE_OVERWEIGHT" => Some(Self::StorageOverweight),
            "STORAGE_NOT_STORABLE" => Some(Self::StorageNotStorable),
            "STORAGE_ITEM_EQUIPPED" => Some(Self::StorageItemEquipped),
            "STORAGE_INVALID_AMOUNT" => Some(Self::StorageInvalidAmount),
            "STORAGE_NOT_OPEN" => Some(Self::StorageNotOpen),
            "STORAGE_BASIC_SKILL_REQUIRED" => Some(Self::StorageBasicSkillRequired),
            _ => None,
        }
    }
}
