//! Headless integration check for locally converted GR2 assets. Never starts the client.

use bevy::{
    animation::AnimationPlugin,
    asset::{AssetPlugin, LoadContext, io::AssetSourceBuilder},
    gltf::{
        GltfMaterial, GltfPlugin,
        extensions::{ErasedGltfExtensionHandler, GltfExtensionHandler, GltfExtensionHandlers},
    },
    mesh::MeshPlugin,
    prelude::*,
    world_serialization::{WorldAssetRoot, WorldSerializationPlugin},
};
use game_engine::domain::entities::{
    character::{components::visual::CharacterDirection, states::AnimationState},
    model_rendering::{Gr2Actor, GuildFlag, ModelRenderingPlugin},
};
use std::{
    path::Path,
    time::{Duration, Instant},
};

/// The normal client uses PbrPlugin's material handler. This equivalent asset-only
/// handler avoids initializing a GPU in the headless integration test.
#[derive(Clone)]
struct StandardMaterials;
impl GltfExtensionHandler for StandardMaterials {
    fn dyn_clone(&self) -> Box<dyn ErasedGltfExtensionHandler> {
        Box::new(self.clone())
    }
    fn on_material(
        &mut self,
        context: &mut LoadContext<'_>,
        _: &gltf::Material,
        _: Handle<GltfMaterial>,
        material: &GltfMaterial,
        label: &str,
    ) {
        context.add_labeled_asset(
            format!("{label}/std"),
            StandardMaterial {
                base_color: material.base_color,
                base_color_channel: material.base_color_channel.clone(),
                base_color_texture: material.base_color_texture.clone(),
                unlit: material.unlit,
                ..default()
            },
        );
    }
    fn on_spawn_mesh_and_material(
        &mut self,
        context: &mut LoadContext<'_>,
        _: &gltf::Primitive,
        _: &gltf::Mesh,
        _: &gltf::Material,
        entity: &mut EntityWorldMut,
        label: &str,
    ) {
        entity.insert(MeshMaterial3d(
            context.get_label_handle::<StandardMaterial>(format!("{label}/std")),
        ));
    }
}

fn loader() -> App {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("assets/data");
    let mut app = App::new();
    app.register_asset_source(
        "ro",
        AssetSourceBuilder::platform_default(root.to_str().unwrap(), None),
    );
    app.insert_resource(bevy::time::TimeUpdateStrategy::ManualDuration(
        Duration::from_millis(16),
    ));
    app.add_plugins((
        MinimalPlugins,
        AssetPlugin::default(),
        ImagePlugin::default(),
        MeshPlugin,
        WorldSerializationPlugin,
        GltfPlugin::default(),
        AnimationPlugin,
    ));
    app.world_mut()
        .resource_mut::<GltfExtensionHandlers>()
        .0
        .write_blocking()
        .push(Box::new(StandardMaterials));
    app.init_asset::<StandardMaterial>()
        .register_type::<MeshMaterial3d<StandardMaterial>>()
        .add_plugins(ModelRenderingPlugin);
    app.finish();
    app.cleanup();
    app
}

#[test]
#[ignore = "requires assets generated by cargo run -p ro-to-lifthrasir-cli -- convert-gr2"]
fn converted_gr2_corpus_loads_and_plays_without_a_window() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("assets/data/models/3dmob");
    let paths: Vec<_> = std::fs::read_dir(&dir)
        .expect("run cargo run -p ro-to-lifthrasir-cli -- convert-gr2 first")
        .map(|entry| entry.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "glb"))
        .collect();
    assert!(!paths.is_empty(), "convert-gr2 must produce model assets");
    let mut app = loader();
    for path in &paths {
        let bytes = std::fs::read(path).unwrap();
        let source = gltf::Gltf::from_slice(&bytes).unwrap();
        assert!(source.default_scene().is_some());
        assert!(source.skins().count() > 0);
        assert!(
            source
                .animations()
                .any(|a| a.name() == Some(lifthrasir_data::gr2::IDLE))
        );
        assert!(
            source
                .images()
                .all(|i| matches!(i.source(), gltf::image::Source::View { .. }))
        );
        let name = path.file_name().unwrap().to_str().unwrap();
        let mut actor = app.world_mut().spawn((
            Gr2Actor {
                model: format!("ro://models/3dmob/{name}"),
            },
            AnimationState::Idle,
            CharacterDirection::default(),
            Transform::default(),
            Visibility::Inherited,
        ));
        if name == "guildflag90_1.glb" {
            actor.insert(GuildFlag {
                guild_id: 0,
                emblem_id: 0,
            });
        }
    }
    let deadline = Instant::now() + Duration::from_secs(20);
    loop {
        app.update();
        let playing = app
            .world_mut()
            .query::<&AnimationPlayer>()
            .iter(app.world())
            .filter(|p| p.playing_animations().next().is_some())
            .count();
        if playing >= paths.len() {
            break;
        }
        assert!(
            Instant::now() < deadline,
            "GR2 scene wiring timed out: {playing}/{} playing",
            paths.len()
        );
        std::thread::sleep(Duration::from_millis(2));
    }
    let flag = app
        .world_mut()
        .query::<(Entity, &Gr2Actor)>()
        .iter(app.world())
        .find(|(_, a)| a.model.ends_with("guildflag90_1.glb"))
        .map(|(e, _)| e)
        .expect("converted corpus includes the guild flag");
    let mut pending = vec![flag];
    let mut poses = Vec::new();
    while let Some(entity) = pending.pop() {
        if app
            .world()
            .get::<bevy::animation::AnimatedBy>(entity)
            .is_some()
        {
            poses.push((entity, *app.world().get::<Transform>(entity).unwrap()));
        }
        if let Some(children) = app.world().get::<Children>(entity) {
            pending.extend(children.iter());
        }
    }
    assert!(!poses.is_empty(), "loaded skeleton has animation targets");
    for _ in 0..60 {
        app.update();
    }
    assert!(
        poses.iter().any(|(entity, previous)| {
            let current = app.world().get::<Transform>(*entity).unwrap();
            !current.rotation.abs_diff_eq(previous.rotation, 1e-4)
                || !current.translation.abs_diff_eq(previous.translation, 1e-4)
        }),
        "Bevy must actually animate the imported flag joints"
    );
    assert_eq!(
        app.world_mut()
            .query::<&WorldAssetRoot>()
            .iter(app.world())
            .count(),
        paths.len()
    );
    assert_eq!(
        app.world_mut().query::<&Window>().iter(app.world()).count(),
        0
    );
    let actors: Vec<_> = app
        .world_mut()
        .query_filtered::<Entity, With<Gr2Actor>>()
        .iter(app.world())
        .collect();
    for actor in actors {
        app.world_mut().entity_mut(actor).despawn();
    }
    app.update();
    assert_eq!(
        app.world_mut().query::<&Mesh3d>().iter(app.world()).count(),
        0
    );
    assert_eq!(
        app.world_mut()
            .query::<&AnimationPlayer>()
            .iter(app.world())
            .count(),
        0
    );
}

#[test]
#[should_panic(expected = "failed to load GR2 model")]
fn missing_converted_model_fails_instead_of_requesting_sprites() {
    let mut app = loader();
    app.world_mut().spawn((
        Gr2Actor {
            model: "ro://models/3dmob/__missing_gr2_test__.glb".into(),
        },
        AnimationState::Idle,
        CharacterDirection::default(),
    ));
    let deadline = Instant::now() + Duration::from_secs(5);
    while Instant::now() < deadline {
        app.update();
        std::thread::sleep(Duration::from_millis(2));
    }
    panic!("missing asset did not reach failure detection");
}
