// This file is @generated by prost-build.
/// Wrapper around every application message. `seq` is a per-sender monotonic
/// counter used for correlation; `body` selects the concrete message. Field
/// numbers are grouped by category: 16-31 control, 32-63 client intents,
/// 64+ authoritative/world.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(uint32, tag = "1")]
    pub seq: u32,
    #[prost(oneof = "envelope::Body", tags = "16, 17, 18, 19, 20")]
    pub body: ::core::option::Option<envelope::Body>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// 16-31: control
        #[prost(message, tag = "16")]
        Hello(super::Hello),
        #[prost(message, tag = "17")]
        HelloAck(super::HelloAck),
        #[prost(message, tag = "18")]
        LoginRequest(super::LoginRequest),
        #[prost(message, tag = "19")]
        LoginResponse(super::LoginResponse),
        #[prost(message, tag = "20")]
        LoginFailed(super::LoginFailed),
    }
}
/// Client -> server, first message on the Control channel after connect.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hello {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub build: ::prost::alloc::string::String,
}
/// Server -> client, response to Hello.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HelloAck {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
}
/// Client -> server, account login request (replaces RO CA_LOGIN).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub client_version: u32,
}
/// One available character server, included in a successful LoginResponse.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharServerInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub port: u32,
    #[prost(uint32, tag = "4")]
    pub user_count: u32,
    #[prost(uint32, tag = "5")]
    pub server_type: u32,
    #[prost(bool, tag = "6")]
    pub is_new: bool,
}
/// Server -> client, successful login (replaces RO AC_ACCEPT_LOGIN).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(uint32, tag = "1")]
    pub account_id: u32,
    #[prost(uint32, tag = "2")]
    pub login_id1: u32,
    #[prost(uint32, tag = "3")]
    pub login_id2: u32,
    #[prost(uint32, tag = "4")]
    pub sex: u32,
    #[prost(string, tag = "5")]
    pub auth_token: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub char_servers: ::prost::alloc::vec::Vec<CharServerInfo>,
}
/// Server -> client, rejected login (replaces RO AC_REFUSE_LOGIN).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginFailed {
    #[prost(uint32, tag = "1")]
    pub reason_code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
