[package]
name = "grf-utils"
version.workspace = true
edition.workspace = true

[[bin]]
name = "grf-utils"
path = "src/main.rs"

[dependencies]
ro-formats = { path = "../ro-formats" }
clap = { workspace = true }
anyhow = { workspace = true }
indicatif = "0.18"
zip = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[profile.release]
strip = true
lto = true
